# Generated by Django 5.2.13 on 2026-05-02 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Domain_name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Duration_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_duration', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Intership_mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_name', models.CharField(max_length=90)),
            ],
        ),
        migrations.RemoveField(
            model_name='internshipcourse',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='internshipcourse',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='internshipcourse',
            name='syllabus',
        ),
        migrations.AddField(
            model_name='internshipcourse',
            name='college_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='internshipcourse',
            name='contact_No',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='internshipcourse',
            name='degree',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='internshipcourse',
            name='department_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='internshipcourse',
            name='email',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='internshipcourse',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshipcourse',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshipcourse',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='internshipcourse',
            name='no_of_members',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshipcourse',
            name='referenceid',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='internshipcourse',
            name='whatsapp_No',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='internshipcourse',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='internshipcourse',
            name='duration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.duration_add'),
        ),
        migrations.AddField(
            model_name='internshipcourse',
            name='intership_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.intership_mode'),
        ),
    ]
