# Generated by Django 5.2.13 on 2026-05-04 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_domain_duration_add_intership_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentIntern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_No', models.CharField(blank=True, max_length=60, null=True)),
                ('whatsapp_no', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.CharField(blank=True, max_length=90, null=True)),
                ('college_name', models.CharField(blank=True, max_length=150, null=True)),
                ('degree', models.CharField(blank=True, max_length=150, null=True)),
                ('department_name', models.CharField(blank=True, max_length=15, null=True)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('referenceid', models.CharField(blank=True, max_length=60, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('address', models.TextField()),
                ('Intern_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.duration_add')),
                ('intership_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.intership_mode')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_proof', models.FileField(blank=True, null=True, upload_to='payment_proof/')),
                ('verify_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='internship.studentintern')),
            ],
        ),
        migrations.DeleteModel(
            name='InternshipCourse',
        ),
    ]
