# Generated by Django 5.2.13 on 2026-05-16 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_studentintern_payment_delete_internshipcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentintern',
            name='fees',
        ),
    ]
