# Generated by Django 5.2.13 on 2026-05-16 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0004_remove_studentintern_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentintern',
            name='address',
        ),
        migrations.AddField(
            model_name='studentintern',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.domain'),
        ),
    ]
