# Generated by Django 5.2.13 on 2026-05-02 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('whatsapp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('college_name', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('reference_no', models.CharField(max_length=100)),
                ('project_title', models.CharField(max_length=200)),
                ('team_members', models.PositiveIntegerField(default=1)),
                ('address', models.TextField()),
                ('project_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_proof', models.FileField(blank=True, null=True, upload_to='payment_proof/')),
                ('verify_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='register_projects.studentproject')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('member_contact', models.CharField(max_length=15)),
                ('member_email', models.EmailField(max_length=254)),
                ('member_department', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='register_projects.studentproject')),
            ],
        ),
    ]
