# Generated by Django 5.2.13 on 2026-05-05 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentproject',
            name='project_title',
        ),
    ]
