# Generated by Django 5.2.13 on 2026-05-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_projects', '0002_remove_studentproject_project_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentproject',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentproject',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='studentproject',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentproject',
            name='name',
        ),
        migrations.RemoveField(
            model_name='studentproject',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='studentproject',
            name='project_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
