# Generated by Django 5.2.13 on 2026-05-09 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_projects', '0004_remove_payment_amount_payment_paid_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentproject',
            name='project_amount',
        ),
    ]
