# Generated by Django 5.2.13 on 2026-05-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_projects', '0005_remove_studentproject_project_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='studentproject',
            name='project_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
