# Generated by Django 5.2.13 on 2026-05-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_projects', '0006_remove_payment_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='pending_amount',
        ),
    ]
