# Generated by Django 5.2.13 on 2026-05-20 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_projects', '0007_remove_payment_pending_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='member_department',
        ),
    ]
