# Generated by Django 5.2.13 on 2026-05-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_domain_duration_add_intership_mode_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttraining',
            name='address',
        ),
    ]
