# Generated by Django 5.2.13 on 2026-05-16 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_remove_studenttraining_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttraining',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.domain'),
        ),
    ]
