# Generated by Django 5.2.13 on 2026-05-16 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0005_remove_studentintern_address_studentintern_domain'),
        ('training', '0004_studenttraining_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttraining',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.domain'),
        ),
        migrations.AlterField(
            model_name='studenttraining',
            name='duration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.duration_add'),
        ),
        migrations.AlterField(
            model_name='studenttraining',
            name='intership_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.intership_mode'),
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='Duration_add',
        ),
        migrations.DeleteModel(
            name='Intership_mode',
        ),
    ]
