# Generated by Django 5.2.13 on 2026-05-20 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_studenttraining_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttraining',
            name='fees',
        ),
    ]
